[project]
name = "bdr-dq"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyoxigraph>=0.4.7",
    "rdflib>=7.1.3",
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]
