PREFIX tern: <https://w3id.org/tern/ontologies/tern/>
PREFIX time: <http://www.w3.org/2006/time#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?observation ?date ?is_recent
WHERE {
  ?observation a tern:Observation .
  ?observation time:hasTime ?ot .
  ?ot time:inXSDgYear ?date .

  BIND(xsd:integer(STR(?date)) AS ?year)

  BIND(IF(?year >= 1900, "recent_20_years", "outdated_20_years") AS ?is_recent)
}
