# This rule checks if the observation has a date (inXSDgYear).
# If date is found → "non_empty", else → "empty".

PREFIX tern:   <https://w3id.org/tern/ontologies/tern/>
PREFIX time:   <http://www.w3.org/2006/time#>
PREFIX dqaf:   <http://example.com/def/dqaf/>
PREFIX sosa:   <http://www.w3.org/ns/sosa/>
PREFIX schema: <http://schema.org/>

INSERT {
  GRAPH dqaf:fullResults {
    ?observation dqaf:hasResult [
      sosa:observedProperty <http://example.com/assess/date_completeness/> ;
      schema:value ?status
    ]
  }
}
WHERE {
  ?observation a tern:Observation .

  # Try to get the date from the observation
  OPTIONAL {
    ?observation time:hasTime ?t .
    ?t time:inXSDgYear ?date .
  }

  # If date exists → non_empty, else → empty
  BIND(
    IF(BOUND(?date), "non_empty", "empty")
    AS ?status
  )
}
