# This rule checks if the date is recent (after 2005) or outdated (before 2005)

PREFIX tern:   <https://w3id.org/tern/ontologies/tern/>
PREFIX time:   <http://www.w3.org/2006/time#>
PREFIX xsd:    <http://www.w3.org/2001/XMLSchema#>
PREFIX dqaf:   <http://example.com/def/dqaf/>
PREFIX sosa:   <http://www.w3.org/ns/sosa/>
PREFIX schema: <http://schema.org/>

INSERT {
  GRAPH dqaf:fullResults {
    ?observation dqaf:hasResult [
      sosa:observedProperty <http://example.com/assess/date_recency/> ;
      schema:value ?is_recent
    ]
  }
}
WHERE {
  # Get the observation and its time
  ?observation a tern:Observation .
  ?observation time:hasTime ?ot .
  ?ot time:inXSDgYear ?date .

  # Change year to number
  BIND(xsd:integer(STR(?date)) AS ?year)

  # If year >= 2005 → recent, else → outdated
  BIND(
    IF(?year >= 2005, "recent_20_years", "outdated_20_years")
    AS ?is_recent
  )
}
